# Вариант 1: мониторинг всех интерфейсов
monitoring: all

# Вариант 2: мониторинг конкретных интерфейсов
# monitoring:
#   - wlan0: all
  # - eth0:
  #     include: 
  #       - 192.168.1.100
  #       - 192.168.1.101
  #     exclude:
  #       - 192.168.1.1

# Вариант 3: мониторинг с детальными настройками
# monitoring:
#   # wlan0: all
#   wlan0:
#     include:
#       - 192.168.1.50
#       - 192.168.1.51
#     exclude:
#       - 192.168.1.1
#   br0:
#     include: all
#     exclude:
#       - 172.16.0.1

# Настройки режимов работы
passive_mode: true
active_mode:
  enabled: true
  interval: 10

# Действия при конфликте
conflict_actions:
  # - log
  # - notify
  # - disable_interface
  # - "/home/almondy/ipwatcher/scripts/log_conflict.sh {interface} {conflict-ip} {adopted-mac}"
  # - "/home/almondy/ipwatcher/scripts/notify_conflict.sh {interface} {conflict-ip} {adopted-mac}"
  # - "sudo /home/almondy/ipwatcher/scripts/disable_interface.sh {interface} {conflict-ip} {adopted-mac}"

# Уровень логирования (DEBUG, INFO, WARNING, ERROR, CRITICAL)
logging: DEBUG
